#/bin/bash
mv maint/temlates/template.c maint/temlates/template.cpp
mv maint/templates/template.h maint/templates/template.hpp
mv tests/src/execute__execute_with_vfs_arg.c tests/src/execute__execute_with_vfs_arg.cpp
mv tests/src/execute__execute_get_external_cmd_opts_from_config.c tests/src/execute__execute_get_external_cmd_opts_from_config.cpp
mv tests/src/editor/editcmd__edit_complete_word_cmd.c tests/src/editor/editcmd__edit_complete_word_cmd.cpp
mv tests/src/vfs/extfs/helpers-list/mc_parse_ls_l.c tests/src/vfs/extfs/helpers-list/mc_parse_ls_l.cpp
mv tests/src/execute__common.c tests/src/execute__common.cpp
mv tests/src/filemanager/examine_cd.c tests/src/filemanager/examine_cd.cpp
mv tests/src/filemanager/filegui_is_wildcarded.c tests/src/filemanager/filegui_is_wildcarded.cpp
mv tests/src/filemanager/exec_get_export_variables_ext.c tests/src/filemanager/exec_get_export_variables_ext.cpp
mv tests/src/filemanager/get_random_hint.c tests/src/filemanager/get_random_hint.cpp
mv tests/src/filemanager/do_cd_command.c tests/src/filemanager/do_cd_command.cpp
mv tests/src/execute__execute_external_editor_or_viewer.c tests/src/execute__execute_external_editor_or_viewer.cpp
mv tests/lib/widget/widget_find_by_id.c tests/lib/widget/widget_find_by_id.cpp
mv tests/lib/widget/complete_engine.c tests/lib/widget/complete_engine.cpp
mv tests/lib/widget/hotkey_equal.c tests/lib/widget/hotkey_equal.cpp
mv tests/lib/widget/group_init_destroy.c tests/lib/widget/group_init_destroy.cpp
mv tests/lib/x_basename.c tests/lib/x_basename.cpp
mv tests/lib/utilunix__my_system-common.c tests/lib/utilunix__my_system-common.cpp
mv tests/lib/serialize.c tests/lib/serialize.cpp
mv tests/lib/strutil/parse_integer.c tests/lib/strutil/parse_integer.cpp
mv tests/lib/strutil/filevercmp.c tests/lib/strutil/filevercmp.cpp
mv tests/lib/strutil/str_verscmp.c tests/lib/strutil/str_verscmp.cpp
mv tests/lib/strutil/replace__str_replace_all.c tests/lib/strutil/replace__str_replace_all.cpp
mv tests/lib/vfs/vfs_adjust_stat.c tests/lib/vfs/vfs_adjust_stat.cpp
mv tests/lib/vfs/vfs_split.c tests/lib/vfs/vfs_split.cpp
mv tests/lib/vfs/path_recode.c tests/lib/vfs/path_recode.cpp
mv tests/lib/vfs/path_serialize.c tests/lib/vfs/path_serialize.cpp
mv tests/lib/vfs/vfs_setup_cwd.c tests/lib/vfs/vfs_setup_cwd.cpp
mv tests/lib/vfs/current_dir.c tests/lib/vfs/current_dir.cpp
mv tests/lib/vfs/vfs_prefix_to_class.c tests/lib/vfs/vfs_prefix_to_class.cpp
mv tests/lib/vfs/relative_cd.c tests/lib/vfs/relative_cd.cpp
mv tests/lib/vfs/path_len.c tests/lib/vfs/path_len.cpp
mv tests/lib/vfs/vfs_path_from_str_flags.c tests/lib/vfs/vfs_path_from_str_flags.cpp
mv tests/lib/vfs/vfs_path_string_convert.c tests/lib/vfs/vfs_path_string_convert.cpp
mv tests/lib/vfs/vfs_s_get_path.c tests/lib/vfs/vfs_s_get_path.cpp
mv tests/lib/vfs/vfs_get_encoding.c tests/lib/vfs/vfs_get_encoding.cpp
mv tests/lib/vfs/canonicalize_pathname.c tests/lib/vfs/canonicalize_pathname.cpp
mv tests/lib/vfs/tempdir.c tests/lib/vfs/tempdir.cpp
mv tests/lib/vfs/path_manipulations.c tests/lib/vfs/path_manipulations.cpp
mv tests/lib/vfs/vfs_parse_ls_lga.c tests/lib/vfs/vfs_parse_ls_lga.cpp
mv tests/lib/vfs/path_cmp.c tests/lib/vfs/path_cmp.cpp
mv tests/lib/search/translate_replace_glob_to_regex.c tests/lib/search/translate_replace_glob_to_regex.cpp
mv tests/lib/search/regex_replace_esc_seq.c tests/lib/search/regex_replace_esc_seq.cpp
mv tests/lib/search/hex_translate_to_regex.c tests/lib/search/hex_translate_to_regex.cpp
mv tests/lib/search/glob_translate_to_regex.c tests/lib/search/glob_translate_to_regex.cpp
mv tests/lib/search/glob_prepare_replace_str.c tests/lib/search/glob_prepare_replace_str.cpp
mv tests/lib/search/regex_process_escape_sequence.c tests/lib/search/regex_process_escape_sequence.cpp
mv tests/lib/mc_build_filename.c tests/lib/mc_build_filename.cpp
mv tests/lib/library_independ.c tests/lib/library_independ.cpp
mv tests/lib/utilunix__my_system-fork_fail.c tests/lib/utilunix__my_system-fork_fail.cpp
mv tests/lib/mc_realpath.c tests/lib/mc_realpath.cpp
mv tests/lib/name_quote.c tests/lib/name_quote.cpp
mv tests/lib/utilunix__my_system-fork_child_shell.c tests/lib/utilunix__my_system-fork_child_shell.cpp
mv tests/lib/mcconfig/user_configs_path.c tests/lib/mcconfig/user_configs_path.cpp
mv tests/lib/mcconfig/config_string.c tests/lib/mcconfig/config_string.cpp
mv tests/lib/utilunix__my_system-fork_child.c tests/lib/utilunix__my_system-fork_child.cpp
mv tests/mctest.h tests/mctest.hpp
mv src/events_init.h src/events_init.hpp
mv src/events_init.c src/events_init.cpp
mv src/usermenu.c src/usermenu.cpp
mv src/keybind-defaults.h src/keybind-defaults.hpp
mv src/execute.h src/execute.hpp
mv src/learn.c src/learn.cpp
mv src/args.c src/args.cpp
mv src/clipboard.h src/clipboard.hpp
mv src/cons.handler.c src/cons.handler.cpp
mv src/execute.c src/execute.cpp
mv src/util.h src/util.hpp
mv src/help.c src/help.cpp
mv src/usermenu.h src/usermenu.hpp
mv src/viewer/dialogs.c src/viewer/dialogs.cpp
mv src/viewer/search.c src/viewer/search.cpp
mv src/viewer/growbuf.c src/viewer/growbuf.cpp
mv src/viewer/hex.c src/viewer/hex.cpp
mv src/viewer/internal.h src/viewer/internal.hpp
mv src/viewer/display.c src/viewer/display.cpp
mv src/viewer/move.c src/viewer/move.cpp
mv src/viewer/inlines.h src/viewer/inlines.hpp
mv src/viewer/lib.c src/viewer/lib.cpp
mv src/viewer/actions_cmd.c src/viewer/actions_cmd.cpp
mv src/viewer/ascii.c src/viewer/ascii.cpp
mv src/viewer/mcviewer.c src/viewer/mcviewer.cpp
mv src/viewer/datasource.c src/viewer/datasource.cpp
mv src/viewer/coord_cache.c src/viewer/coord_cache.cpp
mv src/viewer/nroff.c src/viewer/nroff.cpp
mv src/viewer/mcviewer.h src/viewer/mcviewer.hpp
mv src/textconf.c src/textconf.cpp
mv src/keybind-defaults.c src/keybind-defaults.cpp
mv src/file_history.h src/file_history.hpp
mv src/textconf.h src/textconf.hpp
mv src/help.h src/help.hpp
mv src/editor/edit.c src/editor/edit.cpp
mv src/editor/editcmd.c src/editor/editcmd.cpp
mv src/editor/editbuffer.c src/editor/editbuffer.cpp
mv src/editor/editwidget.c src/editor/editwidget.cpp
mv src/editor/edit.h src/editor/edit.hpp
mv src/editor/etags.c src/editor/etags.cpp
mv src/editor/editoptions.c src/editor/editoptions.cpp
mv src/editor/editcmd_dialogs.c src/editor/editcmd_dialogs.cpp
mv src/editor/spell.h src/editor/spell.hpp
mv src/editor/editbuffer.h src/editor/editbuffer.hpp
mv src/editor/spell_dialogs.h src/editor/spell_dialogs.hpp
mv src/editor/etags.h src/editor/etags.hpp
mv src/editor/syntax.c src/editor/syntax.cpp
mv src/editor/choosesyntax.c src/editor/choosesyntax.cpp
mv src/editor/spell.c src/editor/spell.cpp
mv src/editor/bookmark.c src/editor/bookmark.cpp
mv src/editor/format.c src/editor/format.cpp
mv src/editor/editcmd_dialogs.h src/editor/editcmd_dialogs.hpp
mv src/editor/spell_dialogs.c src/editor/spell_dialogs.cpp
mv src/editor/edit-impl.h src/editor/edit-impl.hpp
mv src/editor/editwidget.h src/editor/editwidget.hpp
mv src/editor/editmenu.c src/editor/editmenu.cpp
mv src/editor/editdraw.c src/editor/editdraw.cpp
mv src/vfs/local/local.h src/vfs/local/local.hpp
mv src/vfs/local/local.c src/vfs/local/local.cpp
mv src/vfs/smbfs/smbfs.c src/vfs/smbfs/smbfs.cpp
mv src/vfs/smbfs/smbfs.h src/vfs/smbfs/smbfs.hpp
mv src/vfs/smbfs/helpers/param/params.c src/vfs/smbfs/helpers/param/params.cpp
mv src/vfs/smbfs/helpers/param/loadparm.c src/vfs/smbfs/helpers/param/loadparm.cpp
mv src/vfs/smbfs/helpers/libsmb/smberr.c src/vfs/smbfs/helpers/libsmb/smberr.cpp
mv src/vfs/smbfs/helpers/libsmb/clientgen.c src/vfs/smbfs/helpers/libsmb/clientgen.cpp
mv src/vfs/smbfs/helpers/libsmb/nmblib.c src/vfs/smbfs/helpers/libsmb/nmblib.cpp
mv src/vfs/smbfs/helpers/libsmb/pwd_cache.c src/vfs/smbfs/helpers/libsmb/pwd_cache.cpp
mv src/vfs/smbfs/helpers/libsmb/smbencrypt.c src/vfs/smbfs/helpers/libsmb/smbencrypt.cpp
mv src/vfs/smbfs/helpers/libsmb/smbdes.c src/vfs/smbfs/helpers/libsmb/smbdes.cpp
mv src/vfs/smbfs/helpers/libsmb/nterr.c src/vfs/smbfs/helpers/libsmb/nterr.cpp
mv src/vfs/smbfs/helpers/libsmb/namequery.c src/vfs/smbfs/helpers/libsmb/namequery.cpp
mv src/vfs/smbfs/helpers/lib/kanji.c src/vfs/smbfs/helpers/lib/kanji.cpp
mv src/vfs/smbfs/helpers/lib/netmask.c src/vfs/smbfs/helpers/lib/netmask.cpp
mv src/vfs/smbfs/helpers/lib/interface.c src/vfs/smbfs/helpers/lib/interface.cpp
mv src/vfs/smbfs/helpers/lib/debug.c src/vfs/smbfs/helpers/lib/debug.cpp
mv src/vfs/smbfs/helpers/lib/username.c src/vfs/smbfs/helpers/lib/username.cpp
mv src/vfs/smbfs/helpers/lib/time.c src/vfs/smbfs/helpers/lib/time.cpp
mv src/vfs/smbfs/helpers/lib/util_str.c src/vfs/smbfs/helpers/lib/util_str.cpp
mv src/vfs/smbfs/helpers/lib/md4.c src/vfs/smbfs/helpers/lib/md4.cpp
mv src/vfs/smbfs/helpers/lib/charcnv.c src/vfs/smbfs/helpers/lib/charcnv.cpp
mv src/vfs/smbfs/helpers/lib/charset.c src/vfs/smbfs/helpers/lib/charset.cpp
mv src/vfs/smbfs/helpers/lib/util_sock.c src/vfs/smbfs/helpers/lib/util_sock.cpp
mv src/vfs/smbfs/helpers/lib/slprintf.c src/vfs/smbfs/helpers/lib/slprintf.cpp
mv src/vfs/smbfs/helpers/lib/util.c src/vfs/smbfs/helpers/lib/util.cpp
mv src/vfs/smbfs/helpers/lib/system.c src/vfs/smbfs/helpers/lib/system.cpp
mv src/vfs/smbfs/helpers/lib/util_file.c src/vfs/smbfs/helpers/lib/util_file.cpp
mv src/vfs/smbfs/helpers/include/nterr.h src/vfs/smbfs/helpers/include/nterr.hpp
mv src/vfs/smbfs/helpers/include/byteorder.h src/vfs/smbfs/helpers/include/byteorder.hpp
mv src/vfs/smbfs/helpers/include/local.h src/vfs/smbfs/helpers/include/local.hpp
mv src/vfs/smbfs/helpers/include/trans2.h src/vfs/smbfs/helpers/include/trans2.hpp
mv src/vfs/smbfs/helpers/include/proto.h src/vfs/smbfs/helpers/include/proto.hpp
mv src/vfs/smbfs/helpers/include/nameserv.h src/vfs/smbfs/helpers/include/nameserv.hpp
mv src/vfs/smbfs/helpers/include/smb.h src/vfs/smbfs/helpers/include/smb.hpp
mv src/vfs/smbfs/helpers/include/includes.h src/vfs/smbfs/helpers/include/includes.hpp
mv src/vfs/smbfs/helpers/include/charset.h src/vfs/smbfs/helpers/include/charset.hpp
mv src/vfs/smbfs/helpers/include/kanji.h src/vfs/smbfs/helpers/include/kanji.hpp
mv src/vfs/smbfs/helpers/include/client.h src/vfs/smbfs/helpers/include/client.hpp
mv src/vfs/smbfs/helpers/include/version.h src/vfs/smbfs/helpers/include/version.hpp
mv src/vfs/undelfs/undelfs.c src/vfs/undelfs/undelfs.cpp
mv src/vfs/undelfs/undelfs.h src/vfs/undelfs/undelfs.hpp
mv src/vfs/plugins_init.h src/vfs/plugins_init.hpp
mv src/vfs/ftpfs/ftpfs.c src/vfs/ftpfs/ftpfs.cpp
mv src/vfs/ftpfs/ftpfs.h src/vfs/ftpfs/ftpfs.hpp
mv src/vfs/sftpfs/internal.h src/vfs/sftpfs/internal.hpp
mv src/vfs/sftpfs/vfs_subclass.c src/vfs/sftpfs/vfs_subclass.cpp
mv src/vfs/sftpfs/init.c src/vfs/sftpfs/init.cpp
mv src/vfs/sftpfs/internal.c src/vfs/sftpfs/internal.cpp
mv src/vfs/sftpfs/vfs_class.c src/vfs/sftpfs/vfs_class.cpp
mv src/vfs/sftpfs/init.h src/vfs/sftpfs/init.hpp
mv src/vfs/sftpfs/file.c src/vfs/sftpfs/file.cpp
mv src/vfs/sftpfs/dir.c src/vfs/sftpfs/dir.cpp
mv src/vfs/sftpfs/connection.c src/vfs/sftpfs/connection.cpp
mv src/vfs/sftpfs/config_parser.c src/vfs/sftpfs/config_parser.cpp
mv src/vfs/extfs/extfs.c src/vfs/extfs/extfs.cpp
mv src/vfs/extfs/extfs.h src/vfs/extfs/extfs.hpp
mv src/vfs/sfs/sfs.h src/vfs/sfs/sfs.hpp
mv src/vfs/sfs/sfs.c src/vfs/sfs/sfs.cpp
mv src/vfs/tar/tar.h src/vfs/tar/tar.hpp
mv src/vfs/tar/tar.c src/vfs/tar/tar.cpp
mv src/vfs/cpio/cpio.h src/vfs/cpio/cpio.hpp
mv src/vfs/cpio/cpio.c src/vfs/cpio/cpio.cpp
mv src/vfs/fish/fish.h src/vfs/fish/fish.hpp
mv src/vfs/fish/fishdef.h src/vfs/fish/fishdef.hpp
mv src/vfs/fish/fish.c src/vfs/fish/fish.cpp
mv src/vfs/plugins_init.c src/vfs/plugins_init.cpp
mv src/clipboard.c src/clipboard.cpp
mv src/background.c src/background.cpp
mv src/file_history.c src/file_history.cpp
mv src/setup.c src/setup.cpp
mv src/selcodepage.c src/selcodepage.cpp
mv src/selcodepage.h src/selcodepage.hpp
mv src/background.h src/background.hpp
mv src/setup.h src/setup.hpp
mv src/filemanager/fileopctx.h src/filemanager/fileopctx.hpp
mv src/filemanager/filenot.h src/filemanager/filenot.hpp
mv src/filemanager/find.c src/filemanager/find.cpp
mv src/filemanager/panel.c src/filemanager/panel.cpp
mv src/filemanager/chown.h src/filemanager/chown.hpp
mv src/filemanager/boxes.c src/filemanager/boxes.cpp
mv src/filemanager/chown.c src/filemanager/chown.cpp
mv src/filemanager/ext.c src/filemanager/ext.cpp
mv src/filemanager/tree.h src/filemanager/tree.hpp
mv src/filemanager/midnight.h src/filemanager/midnight.hpp
mv src/filemanager/info.c src/filemanager/info.cpp
mv src/filemanager/mountlist.c src/filemanager/mountlist.cpp
mv src/filemanager/find.h src/filemanager/find.hpp
mv src/filemanager/fileopctx.c src/filemanager/fileopctx.cpp
mv src/filemanager/boxes.h src/filemanager/boxes.hpp
mv src/filemanager/filenot.c src/filemanager/filenot.cpp
mv src/filemanager/panel.h src/filemanager/panel.hpp
mv src/filemanager/chmod.h src/filemanager/chmod.hpp
mv src/filemanager/filegui.c src/filemanager/filegui.cpp
mv src/filemanager/command.c src/filemanager/command.cpp
mv src/filemanager/file.c src/filemanager/file.cpp
mv src/filemanager/cmd.c src/filemanager/cmd.cpp
mv src/filemanager/info.h src/filemanager/info.hpp
mv src/filemanager/treestore.c src/filemanager/treestore.cpp
mv src/filemanager/layout.c src/filemanager/layout.cpp
mv src/filemanager/mountlist.h src/filemanager/mountlist.hpp
mv src/filemanager/ioblksize.h src/filemanager/ioblksize.hpp
mv src/filemanager/filegui.h src/filemanager/filegui.hpp
mv src/filemanager/cmd.h src/filemanager/cmd.hpp
mv src/filemanager/treestore.h src/filemanager/treestore.hpp
mv src/filemanager/file.h src/filemanager/file.hpp
mv src/filemanager/midnight.c src/filemanager/midnight.cpp
mv src/filemanager/achown.h src/filemanager/achown.hpp
mv src/filemanager/tree.c src/filemanager/tree.cpp
mv src/filemanager/hotlist.h src/filemanager/hotlist.hpp
mv src/filemanager/listmode.h src/filemanager/listmode.hpp
mv src/filemanager/dir.c src/filemanager/dir.cpp
mv src/filemanager/listmode.c src/filemanager/listmode.cpp
mv src/filemanager/panelize.h src/filemanager/panelize.hpp
mv src/filemanager/ext.h src/filemanager/ext.hpp
mv src/filemanager/command.h src/filemanager/command.hpp
mv src/filemanager/chmod.c src/filemanager/chmod.cpp
mv src/filemanager/dir.h src/filemanager/dir.hpp
mv src/filemanager/achown.c src/filemanager/achown.cpp
mv src/filemanager/layout.h src/filemanager/layout.hpp
mv src/filemanager/panelize.c src/filemanager/panelize.cpp
mv src/filemanager/hotlist.c src/filemanager/hotlist.cpp
mv src/learn.h src/learn.hpp
mv src/history.h src/history.hpp
mv src/main.c src/main.cpp
mv src/args.h src/args.hpp
mv src/diffviewer/search.c src/diffviewer/search.cpp
mv src/diffviewer/internal.h src/diffviewer/internal.hpp
mv src/diffviewer/ydiff.h src/diffviewer/ydiff.hpp
mv src/diffviewer/ydiff.c src/diffviewer/ydiff.cpp
mv src/subshell/common.c src/subshell/common.cpp
mv src/subshell/internal.h src/subshell/internal.hpp
mv src/subshell/subshell.h src/subshell/subshell.hpp
mv src/subshell/proxyfunc.c src/subshell/proxyfunc.cpp
mv src/util.c src/util.cpp
mv src/consaver/cons.saver.h src/consaver/cons.saver.hpp
mv src/consaver/cons.saver.c src/consaver/cons.saver.cpp
mv lib/widget/quick.h lib/widget/quick.hpp
mv lib/widget/button.c lib/widget/button.cpp
mv lib/widget/mouse.c lib/widget/mouse.cpp
mv lib/widget/radio.c lib/widget/radio.cpp
mv lib/widget/wtools.h lib/widget/wtools.hpp
mv lib/widget/listbox.h lib/widget/listbox.hpp
mv lib/widget/gauge.h lib/widget/gauge.hpp
mv lib/widget/quick.c lib/widget/quick.cpp
mv lib/widget/menu.h lib/widget/menu.hpp
mv lib/widget/input_complete.c lib/widget/input_complete.cpp
mv lib/widget/frame.h lib/widget/frame.hpp
mv lib/widget/buttonbar.c lib/widget/buttonbar.cpp
mv lib/widget/rect.c lib/widget/rect.cpp
mv lib/widget/hline.h lib/widget/hline.hpp
mv lib/widget/dialog-switch.c lib/widget/dialog-switch.cpp
mv lib/widget/widget-common.c lib/widget/widget-common.cpp
mv lib/widget/check.h lib/widget/check.hpp
mv lib/widget/group.c lib/widget/group.cpp
mv lib/widget/dialog.h lib/widget/dialog.hpp
mv lib/widget/input_complete.h lib/widget/input_complete.hpp
mv lib/widget/check.c lib/widget/check.cpp
mv lib/widget/background.c lib/widget/background.cpp
mv lib/widget/widget-common.h lib/widget/widget-common.hpp
mv lib/widget/menu.c lib/widget/menu.cpp
mv lib/widget/gauge.c lib/widget/gauge.cpp
mv lib/widget/history.c lib/widget/history.cpp
mv lib/widget/label.c lib/widget/label.cpp
mv lib/widget/background.h lib/widget/background.hpp
mv lib/widget/button.h lib/widget/button.hpp
mv lib/widget/input.h lib/widget/input.hpp
mv lib/widget/mouse.h lib/widget/mouse.hpp
mv lib/widget/input.c lib/widget/input.cpp
mv lib/widget/dialog.c lib/widget/dialog.cpp
mv lib/widget/history.h lib/widget/history.hpp
mv lib/widget/label.h lib/widget/label.hpp
mv lib/widget/frame.c lib/widget/frame.cpp
mv lib/widget/listbox.c lib/widget/listbox.cpp
mv lib/widget/groupbox.h lib/widget/groupbox.hpp
mv lib/widget/listbox-window.c lib/widget/listbox-window.cpp
mv lib/widget/dialog-switch.h lib/widget/dialog-switch.hpp
mv lib/widget/wtools.c lib/widget/wtools.cpp
mv lib/widget/listbox-window.h lib/widget/listbox-window.hpp
mv lib/widget/groupbox.c lib/widget/groupbox.cpp
mv lib/widget/hline.c lib/widget/hline.cpp
mv lib/widget/rect.h lib/widget/rect.hpp
mv lib/widget/group.h lib/widget/group.hpp
mv lib/widget/buttonbar.h lib/widget/buttonbar.hpp
mv lib/widget/radio.h lib/widget/radio.hpp
mv lib/utilunix.c lib/utilunix.cpp
mv lib/keybind.c lib/keybind.cpp
mv lib/lock.c lib/lock.cpp
mv lib/hook.c lib/hook.cpp
mv lib/filehighlight.h lib/filehighlight.hpp
mv lib/global.c lib/global.cpp
mv lib/strescape.h lib/strescape.hpp
mv lib/event.h lib/event.hpp
mv lib/charsets.h lib/charsets.hpp
mv lib/serialize.c lib/serialize.cpp
mv lib/serialize.h lib/serialize.hpp
mv lib/shell.h lib/shell.hpp
mv lib/util.h lib/util.hpp
mv lib/strutil/xstrtol.c lib/strutil/xstrtol.cpp
mv lib/strutil/strverscmp.c lib/strutil/strverscmp.cpp
mv lib/strutil/strutil8bit.c lib/strutil/strutil8bit.cpp
mv lib/strutil/replace.c lib/strutil/replace.cpp
mv lib/strutil/strescape.c lib/strutil/strescape.cpp
mv lib/strutil/filevercmp.c lib/strutil/filevercmp.cpp
mv lib/strutil/strutil.c lib/strutil/strutil.cpp
mv lib/strutil/strutilutf8.c lib/strutil/strutilutf8.cpp
mv lib/strutil/strutilascii.c lib/strutil/strutilascii.cpp
mv lib/strutil.h lib/strutil.hpp
mv lib/shell.c lib/shell.cpp
mv lib/utilunix.h lib/utilunix.hpp
mv lib/vfs/xdirentry.h lib/vfs/xdirentry.hpp
mv lib/vfs/vfs.h lib/vfs/vfs.hpp
mv lib/vfs/direntry.c lib/vfs/direntry.cpp
mv lib/vfs/parse_ls_vga.c lib/vfs/parse_ls_vga.cpp
mv lib/vfs/path.c lib/vfs/path.cpp
mv lib/vfs/netutil.h lib/vfs/netutil.hpp
mv lib/vfs/utilvfs.h lib/vfs/utilvfs.hpp
mv lib/vfs/interface.c lib/vfs/interface.cpp
mv lib/vfs/path.h lib/vfs/path.hpp
mv lib/vfs/gc.h lib/vfs/gc.hpp
mv lib/vfs/vfs.c lib/vfs/vfs.cpp
mv lib/vfs/netutil.c lib/vfs/netutil.cpp
mv lib/vfs/utilvfs.c lib/vfs/utilvfs.cpp
mv lib/vfs/gc.c lib/vfs/gc.cpp
mv lib/tty/color.h lib/tty/color.hpp
mv lib/tty/mouse.c lib/tty/mouse.cpp
mv lib/tty/tty-slang.h lib/tty/tty-slang.hpp
mv lib/tty/color-slang.c lib/tty/color-slang.cpp
mv lib/tty/keyxdef.c lib/tty/keyxdef.cpp
mv lib/tty/color-ncurses.c lib/tty/color-ncurses.cpp
mv lib/tty/tty-slang.c lib/tty/tty-slang.cpp
mv lib/tty/win.h lib/tty/win.hpp
mv lib/tty/tty-internal.h lib/tty/tty-internal.hpp
mv lib/tty/color-internal.c lib/tty/color-internal.cpp
mv lib/tty/tty-internal.c lib/tty/tty-internal.cpp
mv lib/tty/key.c lib/tty/key.cpp
mv lib/tty/win.c lib/tty/win.cpp
mv lib/tty/tty.c lib/tty/tty.cpp
mv lib/tty/tty-ncurses.h lib/tty/tty-ncurses.hpp
mv lib/tty/x11conn.c lib/tty/x11conn.cpp
mv lib/tty/color-slang.h lib/tty/color-slang.hpp
mv lib/tty/tty-ncurses.c lib/tty/tty-ncurses.cpp
mv lib/tty/tty.h lib/tty/tty.hpp
mv lib/tty/mouse.h lib/tty/mouse.hpp
mv lib/tty/color.c lib/tty/color.cpp
mv lib/tty/key.h lib/tty/key.hpp
mv lib/tty/x11conn.h lib/tty/x11conn.hpp
mv lib/tty/color-internal.h lib/tty/color-internal.hpp
mv lib/event/event.c lib/event/event.cpp
mv lib/event/internal.h lib/event/internal.hpp
mv lib/event/raise.c lib/event/raise.cpp
mv lib/event/manage.c lib/event/manage.cpp
mv lib/global.h lib/global.hpp
mv lib/search/glob.c lib/search/glob.cpp
mv lib/search/search.c lib/search/search.cpp
mv lib/search/normal.c lib/search/normal.cpp
mv lib/search/hex.c lib/search/hex.cpp
mv lib/search/internal.h lib/search/internal.hpp
mv lib/search/lib.c lib/search/lib.cpp
mv lib/search/regex.c lib/search/regex.cpp
mv lib/fs.h lib/fs.hpp
mv lib/stat-size.h lib/stat-size.hpp
mv lib/logging.c lib/logging.cpp
mv lib/timer.c lib/timer.cpp
mv lib/filehighlight/common.c lib/filehighlight/common.cpp
mv lib/filehighlight/internal.h lib/filehighlight/internal.hpp
mv lib/filehighlight/get-color.c lib/filehighlight/get-color.cpp
mv lib/filehighlight/ini-file-read.c lib/filehighlight/ini-file-read.cpp
mv lib/search.h lib/search.hpp
mv lib/timer.h lib/timer.hpp
mv lib/lock.h lib/lock.hpp
mv lib/mcconfig.h lib/mcconfig.hpp
mv lib/glibcompat.h lib/glibcompat.hpp
mv lib/charsets.c lib/charsets.cpp
mv lib/keybind.h lib/keybind.hpp
mv lib/logging.h lib/logging.hpp
mv lib/event-types.h lib/event-types.hpp
mv lib/unixcompat.h lib/unixcompat.hpp
mv lib/timefmt.c lib/timefmt.cpp
mv lib/hook.h lib/hook.hpp
mv lib/widget.h lib/widget.hpp
mv lib/glibcompat.c lib/glibcompat.cpp
mv lib/skin.h lib/skin.hpp
mv lib/mcconfig/common.c lib/mcconfig/common.cpp
mv lib/mcconfig/paths.c lib/mcconfig/paths.cpp
mv lib/mcconfig/history.c lib/mcconfig/history.cpp
mv lib/mcconfig/get.c lib/mcconfig/get.cpp
mv lib/mcconfig/set.c lib/mcconfig/set.cpp
mv lib/timefmt.h lib/timefmt.hpp
mv lib/util.c lib/util.cpp
mv lib/skin/hc-skins.c lib/skin/hc-skins.cpp
mv lib/skin/common.c lib/skin/common.cpp
mv lib/skin/internal.h lib/skin/internal.hpp
mv lib/skin/ini-file.c lib/skin/ini-file.cpp
mv lib/skin/colors-old.c lib/skin/colors-old.cpp
mv lib/skin/colors.c lib/skin/colors.cpp
mv lib/skin/lines.c lib/skin/lines.cpp
mv lib/fileloc.h lib/fileloc.hpp
